name: Python application

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -v
    - name: make build dir
      run: |
        mkdir -p ./build
    - name: copy PS to build
      run: |
        cp -R ./prediction_service ./build
    - name: copy webapp to build
      run: |
        cp -R ./webapp ./build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./build
  deploy:
      needs: build
      permissions:
        contents: read
        pages: write
        id-token: write
      runs-on: ubuntu-latest
      steps:
        - name: Configure Pages
          uses: actions/configure-pages@v4
        - name: Deploy
          id: deployment
          uses: actions/deploy-pages@v4
          with:
            github_token: ${{ secrets.TOKEN }}
            publish_dir: ./build